# Example GitHub Actions workflow which provides a CI build for your Mbed CE project.

name: Test that this Mbed project compiles

# Change this to "on: push" to run the workflow on every commit instead of when a PR is submitted.
on: pull_request

jobs:
  compile:
    runs-on: ubuntu-latest
    container: ghcr.io/armmbed/mbed-os-env:master-latest
    
    strategy:
      matrix:
        mbed_target: 
          - NUCLEO_F401RE
          - NUCLEO_L476RG
          - NUCLEO_L446RE
          - K64F
          - DISCO_L475VG_IOT01A
          - DISCO_L562QE
          - NUCLEO_WB55RG
          - NRF52_DK
          - ARDUINO_NANO33BLE
          - EP_AGORA
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Python dependencies
        run: |
            python3 -m pip install -r mbed-os/tools/requirements.txt

      - name: Build project for ${{ matrix.mbed_target }}
        run: |
            mkdir build && cd build
            cmake .. -GNinja -DMBED_TARGET=${{ matrix.mbed_target }}
            ninja
